### ISSUE TITLE
usdt sample例子种3地址无法签名

### ISSUE THREAD

**Issue by zhoudaqing** [xuanzhui/cryptocoin-py#1]
已经给您发email了，请查收

**Comment by xuanzhui** [comment]
usdt sample里面的例子只支持开头为1的地址，即只支持pay to public key hash `p2pkh`类型的`utxo`；
开头为3的地址是pay to script hash `p2sh`类型的地址，这样的地址需要知道`redeem script`，通过btc sample里面的 `spend_sh_fund` 来签名;
在构建 `p2sh` 的 usdt transaction时，把 `spend_sh_fund` 中创建 _txs_out 数组的部分改成 usdt 的输出结构即可 
```
_txs_out = [TxOut(total_bal - txn_fee - 546, standard_tx_out_script(tx_ins[0][3])),
                   TxOut(0, binascii.unhexlify(omni_tether_script(send_amount))),
                   TxOut(546, standard_tx_out_script(receiver))]
```

**Comment by zhoudaqing** [comment]
> usdt sample里面的例子只支持开头为1的地址，即只支持pay to public key hash `p2pkh`类型的`utxo`；
> 开头为3的地址是pay to script hash `p2sh`类型的地址，这样的地址需要知道`redeem script`，通过btc sample里面的 `spend_sh_fund` 来签名;
> 在构建 `p2sh` 的 usdt transaction时，把 `spend_sh_fund` 中创建 _txs_out 数组的部分改成 usdt 的输出结构即可
> 
> ```
> _txs_out = [TxOut(total_bal - txn_fee - 546, standard_tx_out_script(tx_ins[0][3])),
>                    TxOut(0, binascii.unhexlify(omni_tether_script(send_amount))),
>                    TxOut(546, standard_tx_out_script(receiver))]
> ```

谢谢您回复，已经按照p2sh方式还是无法创建交易，问题已经您邮箱了，请帮忙看看

**Comment by xuanzhui** [comment]
我看了一下pywallet的代码，个人觉得生成omni地址的方式并不正确，PUBKEY_ADDRESS应该和BTC的一样，都是0x00，另外按照bip44的标准，omni的BIP32_PATH 应该为 "m/44'/200'/..."；
另外usdt的地址是可以和btc的地址共用的，在不严格遵守bip44标准的情况下，可以直接用btc的地址做usdt的地址
